project:
  type: website
  output-dir: docs

website:
  title: "Rachid Sahli"
  description: "Site personnel de Rachid Sahli"
  repo-url: https://github.com/rachidsahli/site
  search: true
  open-graph: true
  twitter-card: true
  
  navbar: 

    
    left:
      - href: index.qmd
        text: Accueil
      - href: projets.qmd
        text: Projets
      - href: blog.qmd
        text: Blog
        
        
  page-footer: "Copyright 2025, Rachid SAHLI"

format:
  html:
    theme: 
          light: litera
          dark: [darkly, styles-dark.scss]
    css: styles.css
    toc: true
    page-layout: full

editor: visual

